### ISSUE TITLE
GCP as a backend

### ISSUE THREAD

**Issue by jcoatgoogle** [lyft/discovery#11]
Shouldn't be hard once https://github.com/lyft/discovery/pull/4 is in, though there is the longer-term question of testing. I guess ideally the model would be inverted a bit...there'd be the core library, and then you could couple  it with the backend of your choice. Those backends would be responsible for testing. Still, I don't know how the python ecosystem deals with that.

This isn't a GCP specific issue... if this is possible, I imagine people will want other backends (especially since the needed functionality is so simple...it's easy to imagine a redis backend, etc etc)

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
