### ISSUE TITLE
refactor configuration

### ISSUE THREAD

**Issue by jcoatgoogle** [lyft/discovery#12]
I'm thinking specifically of the code in

https://github.com/lyft/discovery/blob/master/app/settings.py

This gets back to the modularity mentioned in https://github.com/lyft/discovery/issues/11

In a world where people have different backends, we want a clean way to let the required configuration depend on the pieces that they use.

My sense of one possible way to do this is to have a configuration for the backend, and then let the backends register the configuration that they need, and they'll be responsible for pulling it out.

That said, this file is also a bit of a mess and can be made much cleaner ex any of the above.

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
