### ISSUE TITLE
Doco on how to run this thing?

### ISSUE THREAD

**Issue by SleeperSmith** [lyft/discovery#35]
Hi,

I never used flask. Can we even have just a one liner some where to say how to run this? Flask example says
```
$ pip install Flask
$ FLASK_APP=hello.py flask run
 * Running on http://localhost:5000/
```
And I can't find where's the FLASK_APP either.

Thanks. 😆

**Comment by moderation** [comment]
Agree this would be helpful. For ages I was running as `sudo` but now run from the command line with `gunicorn app:app --workers=2 -k gevent`. I've never been able to successfully modify the default ports. I believe gunicorn is required.

**Comment by cbrianhill** [comment]
I was able to get all the prerequisites by doing `pip install -r requirements.txt` and then run using `gunicorn app:app --workers=2 -k gevent`

**Comment by pcn** [comment]
I've been using bazel recently, so I put together this branch:

https://github.com/pcn/discovery/tree/add-bazel-build

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
