### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by leepand** [lyft/discovery#40]
is there some instruction about how to use?

**Comment by 82398485** [comment]
I also want to know how to use this project.
I try to put it in a docker. let it run ... but i don't know which one is the start pyth code....

**Comment by 82398485** [comment]
Now i can run the project...  I doubt about it can run in k8s?  and can get services from istio autoly?
From the ReadMe ,we just know some restfule interface...  
Have any other restful interface we can get all the services list?
Thanks guru.

**Comment by mikecutalo** [comment]
Thank you for you contribution to this repository.

Closing this Issue as this repository is being archived.
